version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=${POSTGRES_SCHEMA}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?schema=${POSTGRES_SCHEMA}
    depends_on:
      - postgres

volumes:
  postgres-data:
